### ISSUE TITLE
Escape characters in captions

### ISSUE THREAD

**Issue by fabiocolacio** [Mandarancio/scidown#2]
<img width="949" alt="caption1" src="https://user-images.githubusercontent.com/5248352/38442087-f266bac8-399b-11e8-9ec7-5c740420b7cb.png">
<img width="925" alt="caption2" src="https://user-images.githubusercontent.com/5248352/38442088-f2d39db4-399b-11e8-92bc-3486d4a139c2.png">
<img width="903" alt="caption3" src="https://user-images.githubusercontent.com/5248352/38442090-f2f00a30-399b-11e8-90d8-298e93ebdc45.png">

If I want to put parentheses inside of a caption, the closing ``)`` is interpreted as the end of the caption. I can't seem to escape it using the ``\`` character, as shown in the pictures above.

Is there some other escape character in *Scidown*?

**Comment by Mandarancio** [comment]
This is an issue I wanted to fix since a while, I suppose adding using `\(` and `\)` could work, or, I could use `@caption{....}` as well as `@figure{id}`, as the characters `{}` are much less used then the `()`. 
Another, probably better option, is to make the parser smarter, and check if the current `)` is actually closing the caption or another opened parenthesis.

**Comment by fabiocolacio** [comment]
I like the idea of using ``\``, since it is the universal escape character in most languages (including markdown), so it would be intuitive for most people. The other solutions would still help though.

**Comment by Mandarancio** [comment]
In the last commit I added the `\` escape char to captions :)
